server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;

  location = / {
    return 302 /ultimate-tic-tac-toe/;
  }

  location /ultimate-tic-tac-toe/ {
    try_files $uri $uri/ /ultimate-tic-tac-toe/index.html;
  }
}
